import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/assets/globals.css";
import { cn } from "@/app/util/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OTA View",
  description: "Generated by bwsoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-gray-100">
      <body className={cn(inter.className, "h-full")}>{children}</body>
    </html>
  );
}
